name: FoundryMeet
options:
  bundleIdPrefix: com.startupnetwork
targets:
  FoundryMeet:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [FoundryMeet]
    dependencies:
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
    info:
      path: FoundryMeet/Info.plist
      properties:
        UILaunchScreen: {}
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.0.0
